let currentUser = null; 
let allTemplates = []; 
let currentTemplateId = ""; 
let currentRecordId = ""; 
let currentAttemptCount = 0; // 🌟 記錄目前編輯的這份是第幾次
let currentSavedAnswers = {}; 
let globalUserList = []; 
let globalTasks = []; 
let globalHistoryCounts = {}; // 🌟 記錄所有學生做過各模板的歷史次數
let timerStates = { ass: { isRunning: false, start: null, elapsed: 0 } };
let timerRaf = {}; 
let autoSaveInterval = null; 
let canvases = {};
let chartAcgmeInstance = null;
let chartUnitInstance = null;
